config/routes.rb
Rails.application.routes.draw do
  get 'fields/index'
  resources :fields do
    collection { post :import }
  end
  resource :search, only: :show, controller: :search

  root :to => 'search#show'

  get "/pages/:page" => "pages#show"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_keyword, :against => [:field_id, :field_name, :field_type, :field_table, :description, :staff_interface_label, :public_interface_label]
  pg_search_scope :search_by_field_name, :against => :field_name
  pg_search_scope :search_by_table, :against => :field_table


  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    spreadsheet.sheets.each do |s|
      spreadsheet.default_sheet = s
      next if !spreadsheet.first_row
      header = spreadsheet.row(1)

      header.map! do |item|
        break if item.nil? || item.empty?
        item.downcase.parameterize(separator: '_')
      end
      header.push("field_table")
      header.push("field_id")

      (2..spreadsheet.last_row).each do |i|
        next_row = spreadsheet.row(i)
        break if next_row[0].nil? || next_row[0].empty?
        next_row.push(s)
        next_row.push("#{next_row[0]}-#{s}")
        row = Hash[[header, next_row].transpose]
        if row["system_required"] != nil && row["system_required"] =~ /^Required$/i
          row["system_required"] = true
        else
          row["system_required"] = false
        end
        if row["system_generated"] != nil && row["system_generated"] =~ /^The contents of this field are automatically generated by the application\.$/i
          row["system_generated"] = true
        else
          row["system_generated"] = false
        end
        row["field_type"].gsub!(/,/,'') if row["field_type"] != nil
        field = find_by(field_id: row["field_id"]) || new
        field.attributes = row.to_hash
        field.save!
      end
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path)
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.like(field_name)
    field_name.nil? ? [] : where(['field_name LIKE ?', "%#{field_name}%"])
  end

  def self.rebuild_pg_search_documents
    find_each { |record| record.update_pg_search_document }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update]
  attr_accessor :description, :staff_interface_label, :public_interface_label, :system_required, :system_generated, :example_data

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    Field.import(params[:file])
    redirect_to fields_url, notice: "Fields imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:field_name, :field_type, :field_table, :description, :staff_interface_label, :public_interface_label, :system_required, :system_generated, :example_data)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:query].present?
      @fields = Field.search_by_keyword(params[:query])
    else
     @fields = Field.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/fields/_form.html.erb
<%= form_with(model: field, local: true) do |form| %>
  <% if field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :field_name %>
    <%= form.text_field :field_name, id: :field_name, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :field_type %>
    <%= form.text_field :field_type, id: :field_type, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :field_table %>
    <%= form.text_field :field_table, id: :field_table, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :field_description %>
  </div>

  <div class="field">
    <%= form.label :staff_interface_label %>
    <%= form.text_field :staff_interface_label, id: :field_staff_interface_label %>
  </div>

  <div class="field">
    <%= form.label :public_interface_label %>
    <%= form.text_field :public_interface_label, id: :field_public_interface_label %>
  </div>

  <div class="field">
    <%= form.label :system_required %>
    <%= form.check_box :system_required, id: :field_system_required %>
  </div>

  <div class="field">
    <%= form.label :system_generated %>
    <%= form.check_box :system_generated, id: :field_system_generated %>
  </div>

  <div class="field">
    <%= form.label :example_data %>
    <%= form.text_area :example_data, id: :field_example_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/_import.html.erb
<h2>Import Fields</h2>

<span class="btn-file">
  <%= form_tag import_fields_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</span>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fields</h1>

<br>
<br>
<%= render :partial => 'import' %>
<br>
<br>
<%= render :partial => "shared/results" %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Field Name:</strong>
  <%= @field.field_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @field.field_type %>
</p>

<p>
  <strong>Table:</strong>
  <%= @field.field_table %>
</p>

<p>
  <strong>Description:</strong>
  <%= @field.description %>
</p>

<p>
  <strong>Staff interface label:</strong>
  <%= @field.staff_interface_label %>
</p>

<p>
  <strong>Public interface label:</strong>
  <%= @field.public_interface_label %>
</p>

<p>
  <strong>System required:</strong>
  <%= @field.system_required %>
</p>

<p>
  <strong>System generated:</strong>
  <%= @field.system_generated %>
</p>

<p>
  <strong>Example data:</strong>
  <%= @field.example_data %>
</p>

<!-- <%= link_to 'Edit', edit_field_path(@field) %> |  -->
<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-106105528-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-106105528-2');
    </script>

    <title>ArchivesSpace Data Dictionary (BETA version)</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container navbar-branding">
      <%= image_tag "archivesspace.small.png"%>
      <h1>Welcome to the ArchivesSpace Data Dictionary (BETA version)</h1>
    </div>
    <br/>
    <br/>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>The ArchivesSpace Data Dictionary</h2>

<p>The ArchivesSpace Data Dictionary provides a simple mechanism to identify
  information about the data elements in the ArchivesSpace database schema.

<p>The current search capability searches all fields included in the database.</p>

<p><strong>NOTE: As of January 31, 2018, this is a BETA version that has not been
  officially released.</strong> Please send feedback by emailing
  laney.mcglohon@lyrasis.org or submitting an issue to the
  <a href="https://github.com/lmcglohon/data-dictionary">GitHub repository</a>.</p>

<h3>Intended Use</h3>
<p>The information in this application is expected to be used by the ArchivesSpace
  community to determine where data is stored in the ArchivesSpace database along
  with how the data is displayed in the staff and public user interfaces. We expect
  it will be helpful for a variety of purposes, including writing reports, working
  with the ArchivesSpace API, and writing code for functions in the application.</p>

<h3>Future enhancements</h3>
<p>We anticipate adding additional data points and functionality over time to
  enhance the usefulness of this application.</p>
<p>Planned enhancements include:</p>
<ul>
<li>Adding crosswalk information for the following metadata standards:
<ul>
<li>EAD</li>
<li>MARC</li>
<li>MODS</li>
<li>DC</li>
</ul>
</li>

<li>Highlighting results in context</li>
<li>Sort capability from column headings</li>
<li>Ability to search specific fields</li>
 <li>Exporting of search results</li>
</ul>

<h3>Special Thanks</h3>

<p>This application would not be possible without the work of the ArchivesSpace
  User Advisory Council Reports Sub-team, particularly the extraordinary efforts
  by Nancy Enneking.</p>

<%= link_to 'Back', :back %>

app/views/search/show.html.erb
<%= link_to "About", 'pages/about', class: 'page-link'%>
<br/>
<br/>
<form id='search' method='get' action='/search' >
    <input type='text' id='query' name='query' />
    <input type='submit' value='Search' />
</form>
<br>
<br>

<div class='results'>
  <%= render :partial => "shared/results" %>
</div>

app/views/shared/_results.html.erb
<div style="overflow-x:auto;">

  <ol class='results'>
    <table>
      <thead>
        <tr>
          <th>Table</th>
          <th>Field Name</th>
          <th>Description</th>
          <th>Example data</th>
        </tr>
      </thead>

      <tbody>
        <% @fields.each do |field| %>
          <tr>
            <td><%= field.field_table %></td>
            <td><%= link_to(field.field_name, [field]) %></td>
            <td><%= field.description %></td>
            <td><%= field.example_data %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </ol>
</div>